elasticsearch:
  image: elasticsearch:5.1.1
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - ./es_data/:/usr/share/elasticsearch/data/
kibana:
  image: kibana:5
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
